# Generated by Django 5.0.1 on 2024-02-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('editor', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
