# Generated by Django 5.0.1 on 2024-02-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
