# Generated by Django 5.0.1 on 2024-02-01 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identificationUser', models.IntegerField(default=None, unique=True, verbose_name='Identificacion')),
                ('emailUser', models.EmailField(max_length=100, unique=True, verbose_name='correo electrónico')),
                ('firstnameUser', models.CharField(max_length=60, verbose_name='Nombre')),
                ('lastnameUser', models.CharField(max_length=60, null=True, verbose_name='Apellido')),
                ('ageUser', models.IntegerField(null=True, verbose_name='Edad')),
                ('phoneUser', models.CharField(max_length=15, verbose_name='Telefono')),
                ('appointmentUser', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Fecha de cita')),
                ('imageUser', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('writerUser', models.BooleanField(default=False)),
                ('activeUser', models.BooleanField(default=True)),
                ('adminUser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
